from models.user import User
from enum import Enum

class Menu(Enum):
    LOGIN = 0
    SUPER_ADMIN_MAIN = 1
    SUPER_ADMIN_CREATE_ACCOUNT = 2
    SUPER_ADMIN_UPDATE_ACCOUNT = 3
    SUPER_ADMIN_DELETE_ACCOUNT = 4
    SUPER_ADMIN_LIST_USERS = 5
    SUPER_ADMIN_VIEW_LOGS = 6
    SUPER_ADMIN_MANAGE_SCOOTERS = 7
    SUPER_ADMIN_LIST_SCOOTERS = 324
    SUPER_ADMIN_CREATE_SCOOTER = 237
    SUPER_ADMIN_UPDATE_SCOOTER = 4241
    SUPER_ADMIN_DELETE_SCOOTER = 231

    SYSTEM_ADMIN_MAIN = 8
    SYSTEM_ADMIN_LIST_USERS = 65
    SYSTEM_ADMIN_CREATE_ACCOUNT = 9
    SYSTEM_ADMIN_UPDATE_ACCOUNT = 10
    SYSTEM_ADMIN_DELETE_ACCOUNT = 11
    SYSTEM_ADMIN_VIEW_LOGS = 12
    SYSTEM_ADMIN_MANAGE_SCOOTERS = 135
    SYSTEM_ADMIN_LIST_SCOOTERS = 683
    SYSTEM_ADMIN_CREATE_SCOOTER = 875
    SYSTEM_ADMIN_UPDATE_SCOOTER = 132
    SYSTEM_ADMIN_DELETE_SCOOTER = 9432


    SERVICE_ENGINEER_MAIN = 13
    
menu_stack: list = []
current_user: User | None = None
last_menu_choice: str = "List Users"
