from models.user import User
from enum import Enum

class Menu(Enum):
    LOGIN = 0
    SUPER_ADMIN_MAIN = 1
    SUPER_ADMIN_CREATE_ACCOUNT = 2
    SUPER_ADMIN_UPDATE_ACCOUNT = 3
    SUPER_ADMIN_DELETE_ACCOUNT = 4
    SUPER_ADMIN_LIST_USERS = 5
    SUPER_ADMIN_VIEW_LOGS = 6
    SUPER_ADMIN_MANAGE_SCOOTERS = 7
    SUPER_ADMIN_LIST_SCOOTERS = 8
    SUPER_ADMIN_CREATE_SCOOTER = 9
    SUPER_ADMIN_UPDATE_SCOOTER = 10
    SUPER_ADMIN_DELETE_SCOOTER = 11

    SYSTEM_ADMIN_MAIN = 12
    SYSTEM_ADMIN_LIST_USERS = 13
    SYSTEM_ADMIN_CREATE_ACCOUNT = 14
    SYSTEM_ADMIN_UPDATE_ACCOUNT = 15
    SYSTEM_ADMIN_DELETE_ACCOUNT = 16
    SYSTEM_ADMIN_VIEW_LOGS = 17
    SYSTEM_ADMIN_MANAGE_SCOOTERS = 18
    SYSTEM_ADMIN_LIST_SCOOTERS = 19
    SYSTEM_ADMIN_CREATE_SCOOTER = 20
    SYSTEM_ADMIN_UPDATE_SCOOTER = 21
    SYSTEM_ADMIN_DELETE_SCOOTER = 22

    SERVICE_ENGINEER_MAIN = 23
    
menu_stack: list = []
current_user: User | None = None
last_menu_choice: str = "List Users"
