from models.user import User
from enum import Enum

class Menu(Enum):
    LOGIN = 0
    SUPER_ADMIN_MAIN = 1
    SUPER_ADMIN_MANAGE_ACCOUNTS = 81
    SUPER_ADMIN_CREATE_ACCOUNT = 2
    SUPER_ADMIN_UPDATE_ACCOUNT = 3
    SUPER_ADMIN_DELETE_ACCOUNT = 4
    SUPER_ADMIN_LIST_USERS = 5
    SUPER_ADMIN_VIEW_LOGS = 6

    SYSTEM_ADMIN_MAIN = 7
    SYSTEM_ADMIN_LIST_USERS = 8
    SYSTEM_ADMIN_CREATE_ACCOUNT = 9
    SYSTEM_ADMIN_UPDATE_ACCOUNT = 10
    SYSTEM_ADMIN_DELETE_ACCOUNT = 11
    SYSTEM_ADMIN_VIEW_LOGS = 12

    SERVICE_ENGINEER_MAIN = 13

    SUPER_ADMIN_MANAGE_SCOOTERS = 80
    SUPER_ADMIN_LIST_SCOOTERS = 14
    SUPER_ADMIN_CREATE_SCOOTER = 15
    SUPER_ADMIN_UPDATE_SCOOTER = 16
    SUPER_ADMIN_DELETE_SCOOTER = 17

    SYSTEM_ADMIN_LIST_SCOOTERS = 18
    SYSTEM_ADMIN_CREATE_SCOOTER = 19
    SYSTEM_ADMIN_UPDATE_SCOOTER = 20
    SYSTEM_ADMIN_DELETE_SCOOTER = 21

    SERVICE_ENGINEER_LIST_SCOOTERS = 22
    SERVICE_ENGINEER_CREATE_SCOOTER = 23
    SERVICE_ENGINEER_UPDATE_SCOOTER = 24
    SERVICE_ENGINEER_DELETE_SCOOTER = 25

menu_stack: list = []
current_user: User | None = None
last_menu_choice: str = "List Users"
